### ISSUE TITLE
Referencing 2 images with the same content results one is failing with 404

### ISSUE THREAD

**Issue by sashee** [ixti/jekyll-assets#112]
I have 2 images with the same content (so the hash is the same), and when I'm using the {% image %} tag on both of them, only 1 gets copied, so the other one fails to load in the browser.

I can provide a minimal example, but it's easy to reproduce:
- In the _assets/images folder, have 2 images: test1.jpg and test2.jpg with the same content
- In a HTML, put this: {% image test1.jpg %} {% image test2.jpg %}
- Load in a browser, you'll get a 404 for the test2. ( GET http://localhost:4000/assets/test2-1125293dfa76414fbcb4929478b7613e.jpg 404 (Not Found))
- ls _site/assets/ | grep test.*.jpg => test1-1125293dfa76414fbcb4929478b7613e.jpg

**Comment by benben** [comment]
same here! how should we handle this case?

**Comment by sashee** [comment]
In my situation, I've removed the duplicate and referenced the same image file.

**Comment by genexp** [comment]
I think the solution is to copy it twice.  There's nothing wrong with a
duplicate
