### ISSUE TITLE
Nil params on initialize, problem with jekyll-assets on markup pages

### ISSUE THREAD

**Issue by coneybeare** [ixti/jekyll-assets#121]
I have a strange error in my jekyll site that is using this assets plugin.

I have a html include file that calls asset_plugin like `{{ video['poster'] | asset_path }}` and all works correctly when the video is specified by the yaml front matter and plugins I have setup.
The include which has this line is in the include tree of default.html when used normally.

In a specific case, I am trying to include this html file from the markup post using the standard method, but jekyll-assets fails to find/copy the resources when I do this. If I change the post extension to .html, the jekyll-assets plugin works as expected, but I do not get the benefits of a markup syntax in my posts.

The specific error I am seeing is `Liquid Exception: undefined method strip' for nil:NilClass` with a stack trace that bails on [this line](https://github.com/ixti/jekyll-assets/blob/master/lib/jekyll/assets_plugin/renderer.rb#L27) due to `params` being nil. Note that the params are not actually nil, and that the values passed into asset_tag are tested to be present and valid.

So, my question is, how can I make the jekyll-assets plugin play nicely when included from a markup page rather than an html page?

**Comment by ixti** [comment]
:D Additional info will help significantly. Alternatively, an example sandbox that I can play with to reproduce this error will help as well :D

**Comment by coneybeare** [comment]
It appears the problem stemmed from an automatic page generation plugin I am using which passed the posts files through mardownify. I tried adjusting the orders of the plugin calls and started to dig in, but then decided on a different page design that didn't require the assets. Thus, I didn't find the root cause, nor did I fix it, but we can close this anyway.

**Comment by phillipadsmith** [comment]
Having this issue too:

```{{ share_image_environment.jpg | asset_path }}``` 

Produces:              

```Error: undefined method `strip' for nil:NilClass```

jekyll 2.4.0
jekyll-assets-0.12.1

Any thoughts appreciated.

**Comment by phillipadsmith** [comment]
Ignore that question. Bad quoting.
