### ISSUE TITLE
It fails on github but works locally with some warnings

### ISSUE THREAD

**Issue by bl4ckdu5t** [ixti/jekyll-assets#122]
Usually when I run `jekyll serve` I get this warning before the server loads
```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 2.7)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```
I ignored this warning as I really didn't know what I was expected to do. Everything works fine besides that but after pushing to github, I got the following message:
```
The page build failed with the following error:
The tag 'stylesheet' in _includes/head.html is not a recognized liquid tag.
```
I believe this is where I used the jekyll-assets {% stylesheet app %}

Here is my blog source: <https://github.com/bl4ckdu5t/bl4ckdu5t.github.io>

**Comment by ixti** [comment]
It's a limitation of [GitHub Pages](http://pages.github.com/). You can see more info on Jekyll's [plugins](http://jekyllrb.com/docs/plugins/) documentation.

In other words you can't use any plugins with GitHub Pages directly. Your only option here is to build your website locally and then pushing it to GitHub. I use Rakefile to achieve that with minimum efforts: http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html

**Comment by bl4ckdu5t** [comment]
Thanks I just read the blog post and I find it really usefult
