### ISSUE TITLE
Sprockets error when using asset-url

### ISSUE THREAD

**Issue by cgansen** [ixti/jekyll-assets#123]
First off, thanks for an amazing tool. jekyll-assets is fun to work with and has been very useful.

I am running into trouble using `asset-url()`. Each time I use it in a `.scss` file, I get the following error: 

```
$ bundle exec jekyll build  --config _config.yml,_config_dev.yml --trace
Configuration file: _config.yml
Configuration file: _config_dev.yml
            Source: src
       Destination: site
      Generating...
/Users/cgansen/.rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/sprockets-sass-1.3.1/lib/sprockets/sass/functions.rb:128:in `sprockets_context': undefined method `[]' for nil:NilClass (NoMethodError)
```

(the full stacktrace is available at https://gist.github.com/cgansen/686da5682d802beb7fe4)

When I remove the `asset-url(filename)` call from my .scss file, everything builds normally.

Any tips? Anything else I can provide to help debug this issue?

Here's a gist with relevant environment data (bundle versions, etc): https://gist.github.com/cgansen/e7c2bba76e85c19c4401

**Comment by cgansen** [comment]
I found that this issue went away when I removed an errant `gem 'jeykll-sass'` in my Gemfile. False alarm!

**Comment by ixti** [comment]
:D Sorry I had no time to take a look. Glad you found the reason. :+1:
