### ISSUE TITLE
Relative path for `Sprockets.append_path`

### ISSUE THREAD

**Issue by LimeBlast** [ixti/jekyll-assets#124]
I'm trying to add some paths to sprockets, but I can't figure out how to make it work with relative paths.

My `_config.yml` file has the source set to `./app`, and the path I was to include is under this. Following the instructions provided, I've updated my `ext.rb` file as shown below:

    require "sprockets"
    Sprockets.append_path "/Users/Daniel/Projects/static-site-generator/bower_components"

Which works - but I don't want this to be an absolute path, I want it to be a relative one. I've tried setting it to each of the following, but none of them work:

- `bower_components`
- `./bower_components`
- `../bower_components`

I hope someone can help. Thank you.

PS, my source code is here: https://github.com/LimeBlast/static-site-generator

**Comment by ixti** [comment]
You should either override lookup paths of Jekyll/Assets plugin (recommended):

``` patch
diff --git a/_config.yml b/_config.yml
index 1c39362..56ebd87 100644
--- a/_config.yml
+++ b/_config.yml
@@ -13,3 +13,10 @@ permalink: pretty
 # Paths
 source:      ./app
 destination: ./dest
+
+assets:
+  sources:
+    - _assets/javascripts
+    - _assets/stylesheets
+    - _assets/images
+    - ../bower_components
```

Or use absolute paths when you append them to Sprockets global lookup paths collection directly:

``` patch
diff --git a/app/_plugins/ext.rb b/app/_plugins/ext.rb
index e288ed9..2300886 100644
--- a/app/_plugins/ext.rb
+++ b/app/_plugins/ext.rb
@@ -1,4 +1,4 @@
 require "jekyll-assets"
 require "sprockets"
 
-Sprockets.append_path "bower_components"
+Sprockets.append_path File.expand_path("../../../bower_components", __FILE__)
```

Patches are applicable for your source code ;))

**Comment by ixti** [comment]
Just to explain. When you append path to Sprocket's global collection, you append paths **relative** to sprockets gem. So:

``` ruby
Sprockets.append_path "bower_components"
```

Resolves path to something like this:

```
/home/ixti/.gem/ruby/2.1.5/gems/sprockets-2.12.3/lib/bower_components
```
```

**Comment by LimeBlast** [comment]
Ah, cool. Thank you for the answer, I'll give that a go :)

**Comment by LimeBlast** [comment]
[That worked perfectly](https://github.com/LimeBlast/static-site-generator/commit/c6e0883cfd27336b8e80ad57d5cbc5c912d2d8a1), thank you.

**Comment by ixti** [comment]
Awesome! :D
