### ISSUE TITLE
respect Jekyll's site.baseurl

### ISSUE THREAD

**Issue by afeld** [ixti/jekyll-assets#125]
Unless the `assets.baseurl` config value is set, it would make sense to default to prepending the top-level `baseurl` config to `/assets`. In other words, for:

```yaml
# _config.yml
baseurl: /foo
```

`{% asset_url 'app.js' %}` should produce `/foo/assets/app-XXX.js`. Sound reasonable?

**Comment by afeld** [comment]
FYI for anyone else, [the workaround](https://github.com/18F/hub/commit/fc37050fba75ecfda54f0935c3f95eb1415b2b3b#diff-21f69f3db2b584e48657212aee1b692bR5) is to set the `assets.baseurl` explicitly:

```yaml
baseurl: /foo
assets:
  baseurl: /foo/assets
```

**Comment by ixti** [comment]
Released as `0.13.0`

**Comment by amw** [comment]
Looks like this issue creeped up again in the 2.0 pre-releases.

**Comment by amw** [comment]
Now there's a `prefix` configuration, but it changes both the asset links and placement in `_site` directory. `baseurl` only changes links, but doesn't create a subdirectory inside `_site`.

**Comment by envygeeks** [comment]
File a new ticket and describe the problem in more detail and I'll fix it. Thanks.
